// Generated by CoffeeScript 1.9.1
var fs;

fs = require('fs');

module.exports = function(exe, params) {
  var getparams, getpath;
  getpath = exe.build(params.__path);
  getparams = exe.build(params.__params);
  return function(cb) {
    return getparams(function(err, params) {
      return getpath(function(err, path) {
        if (err != null) {
          return cb(err);
        }
        return fs.readFile(path, params, function(err, buf) {
          if (err != null) {
            return cb(err);
          }
          if (typeof buf === 'string') {
            return cb(null, buf);
          } else {
            return cb(null, buf.toString());
          }
        });
      });
    });
  };
};
